apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-pagamento-deployment
spec:
  selector:
    matchLabels:
      app: mongodb-pagamento
  template:
    metadata:
      labels:
        app: mongodb-pagamento
    spec:
      containers:
      - name: mongodb-pagamento
        image: mongo
        command: ["/bin/sh"]
        args: ["-c" , "mongod --bind_ip_all --port 27017"]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        - name: MONGO_INITDB_USERNAME
          value: root
        - name: MONGO_INITDB_PASSWORD
          value: root
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-pagamento-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-pagamento-storage
        persistentVolumeClaim:
          claimName: mongodb-pagamento-pvc
