apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jlapp-pagamento-deployment.yaml
  - jlapp-pagamento-service.yaml
  - service-account.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml

images:
  - name: jlapp-pagamento
    newName: jlapp-pagamento
    newTag: latest
